# Generated by Django 4.0.5 on 2022-07-04 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='type',
            field=models.CharField(choices=[('Компьютеры', 'Computers'), ('Ноутбуки', 'Notebooks')], default='Компьютеры', max_length=120, verbose_name='Тип'),
        ),
    ]
